# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Color.create(name: "BLANCO", hex_code: "#FFFFFF")
Color.create(name: "AZUR", hex_code: "#F0FFFF")
Color.create(name: "CREMA", hex_code: "#F5FFFA")
Color.create(name: "NIEVE", hex_code: "#FFFAFA")
Color.create(name: "MARFIL", hex_code: "#FFFFF0")
Color.create(name: "BLANCO FANTASMA", hex_code: "#F8F8FF")
Color.create(name: "BLANCO FLORAL", hex_code: "#FFFAF0")
Color.create(name: "AZUL ALICIA", hex_code: "#F0F8FF")
Color.create(name: "CIAN CLARO", hex_code: "#E0FFFF")
Color.create(name: "MELÓN VERDE", hex_code: "#F0FFF0")
Color.create(name: "AMARILLO CLARO", hex_code: "#FFFFE0")
Color.create(name: "CONCHA", hex_code: "#FFF5EE")
Color.create(name: "SONROJO LAVANDA", hex_code: "#FFF0F5")
Color.create(name: "HUMO BLANCO", hex_code: "#F5F5F5")
Color.create(name: "ENCAJE ANTIGUO", hex_code: "#FDF5E6")
Color.create(name: "SEDA DE MAÍZ", hex_code: "#FFF8DC")
Color.create(name: "LINO", hex_code: "#FAF0E6")
Color.create(name: "AMARILLO ALAMBRE DORADO CLARO", hex_code: "#FAFAD2")
Color.create(name: "GASA LIMÓN", hex_code: "#FFFACD")
Color.create(name: "BEIGE", hex_code: "#F5F5DC")
Color.create(name: "LAVANDA", hex_code: "#E6E6FA")
Color.create(name: "BATIDO DE PAPAYA", hex_code: "#FFEFD5")
Color.create(name: "ROSA BRUMOSA", hex_code: "#FFE4E1")
Color.create(name: "BLANCO ANTIGUO", hex_code: "#FAEBD7")
Color.create(name: "BLANCO ALMENDRA", hex_code: "#FFEBCD")
Color.create(name: "SOPA", hex_code: "#FFE4C4")
Color.create(name: "TURQUESA PÁLIDO", hex_code: "#AFEEEE")
Color.create(name: "MOCASÍN", hex_code: "#FFE4B5")
Color.create(name: "GAINSBORO", hex_code: "#DCDCDC")
Color.create(name: "SOPLIDO MELOCOTÓN", hex_code: "#FFDAB9")
Color.create(name: "BLANCO NAVAJO", hex_code: "#FFDEAD")
Color.create(name: "DORADO ALAMBRE PÁLIDO", hex_code: "#EEE8AA")
Color.create(name: "TRIGO", hex_code: "#F5DEB3")
Color.create(name: "POLVO AZUL", hex_code: "#B0E0E6")
Color.create(name: "AGUAMARINA", hex_code: "#7FFFD4")
Color.create(name: "GRIS CLARO", hex_code: "#D3D3D3")
Color.create(name: "ROSA", hex_code: "#FFC0CB")
Color.create(name: "AZUL CLARO", hex_code: "#ADD8E6")
Color.create(name: "CARDO", hex_code: "#D8BFD8")
Color.create(name: "ROSA CLARO", hex_code: "#FFB6C1")
Color.create(name: "AZUL CIELO CLARO", hex_code: "#87CEFA")
Color.create(name: "VERDE PÁLIDO", hex_code: "#98FB98")
Color.create(name: "AZUL ACERO CLARO", hex_code: "#B0C4DE")
Color.create(name: "CAQUI", hex_code: "#F0D58C")
Color.create(name: "AZUL CIELO", hex_code: "#87CEEB")
Color.create(name: "AGUA", hex_code: "#00FFFF")
Color.create(name: "CIAN", hex_code: "#00FFFF")
Color.create(name: "PLATA", hex_code: "#C0C0C0")
Color.create(name: "CIRUELA", hex_code: "#DDA0DD")
Color.create(name: "GRIS", hex_code: "#BEBEBE")
Color.create(name: "VERDE CLARO", hex_code: "#90EE90")
Color.create(name: "VIOLETA", hex_code: "#EE82EE")
Color.create(name: "AMARILLO", hex_code: "#FFFF00")
Color.create(name: "TURQUESA", hex_code: "#40E0D0")
Color.create(name: "MADERA FORNIDA", hex_code: "#DEB887")
Color.create(name: "AMARILLO VERDE", hex_code: "#ADFF2F")
Color.create(name: "BRONCEADO", hex_code: "#D2B48C")
Color.create(name: "TURQUESA MEDIO", hex_code: "#48D1CC")
Color.create(name: "SALMÓN CLARO", hex_code: "#FFA07A")
Color.create(name: "AGUAMARINA MEDIO", hex_code: "#66CDAA")
Color.create(name: "GRIS OSCURO", hex_code: "#A9A9A9")
Color.create(name: "ORQUÍDEA", hex_code: "#DA70D6")
Color.create(name: "VERDE MAR INTENSO", hex_code: "#8FBC8F")
Color.create(name: "AZUL CIELO INTENSO", hex_code: "#00BFFF")
Color.create(name: "MARRÓN ARENA", hex_code: "#F4A460")
Color.create(name: "DORADO", hex_code: "#FFD700")
Color.create(name: "VERDE PRIMAVERA MEDIO", hex_code: "#00FA9A")
Color.create(name: "CAQUI OSCURO", hex_code: "#BDB76B")
Color.create(name: "ACIANO AZUL", hex_code: "#6495ED")
Color.create(name: "ROSA CALIENTE", hex_code: "#FF69B4")
Color.create(name: "SALMÓN OSCURO", hex_code: "#E9967A")
Color.create(name: "TURQUESA OSCURO", hex_code: "#00CED1")
Color.create(name: "VERDE PRIMAVERA", hex_code: "#00FF7F")
Color.create(name: "CORAL CLARO", hex_code: "#F08080")
Color.create(name: "MARRÓN ROSADO", hex_code: "#BC8F8F")
Color.create(name: "SALMÓN", hex_code: "#FA8072")
Color.create(name: "CHARTREUSE", hex_code: "#7FFF00")
Color.create(name: "PÚRPURA MEDIO", hex_code: "#9370DB")
Color.create(name: "VERDE CÉSPED", hex_code: "#7CFC00")
Color.create(name: "AZUL DODGER", hex_code: "#1E90FF")
Color.create(name: "VERDE AMARILLO", hex_code: "#9ACD32")
Color.create(name: "VIOLETA ROJO PÁLIDO", hex_code: "#DB7093")
Color.create(name: "AZUL PIZARRA MEDIO", hex_code: "#7B68EE")
Color.create(name: "ORQUÍDEA MEDIO", hex_code: "#BA55D3")
Color.create(name: "CORAL", hex_code: "#FF7F50")
Color.create(name: "AZUL CADETE", hex_code: "#5F9EA0")
Color.create(name: "VERDE MAR CLARO", hex_code: "#20B2AA")
Color.create(name: "DORADO ALAMBRE", hex_code: "#DAA520")
Color.create(name: "NARANJA", hex_code: "#FFA500")
Color.create(name: "GRIS PIZARRA CLARO", hex_code: "#778899")
Color.create(name: "FUCSIA", hex_code: "#FF00FF")
Color.create(name: "MAGENTA", hex_code: "#FF00FF")
Color.create(name: "VERDE MAR MEDIO", hex_code: "#3CB371")
Color.create(name: "PERÚ", hex_code: "#CD853F")
Color.create(name: "AZUL ACERO", hex_code: "#4682B4")
Color.create(name: "AZUL REAL", hex_code: "#4169E1")
Color.create(name: "GRIS PIZARRA", hex_code: "#708090")
Color.create(name: "TOMATE", hex_code: "#FF6347")
Color.create(name: "NARANJA OSCURO", hex_code: "#FF8C00")
Color.create(name: "AZUL PIZARRA", hex_code: "#6A5ACD")
Color.create(name: "VERDE LIMA", hex_code: "#32CD32")
Color.create(name: "LIMA", hex_code: "#00FF00")
Color.create(name: "ROJO INDIO", hex_code: "#CD5C5C")
Color.create(name: "ORQUÍDEA OSCURO", hex_code: "#9932CC")
Color.create(name: "AZUL VIOLETA", hex_code: "#8A2BE2")
Color.create(name: "ROSA INTENSO", hex_code: "#FF1493")
Color.create(name: "DORADO ALAMBRE OSCURO", hex_code: "#B8860B")
Color.create(name: "CHOCOLATE", hex_code: "#D2691E")
Color.create(name: "CIAN OSCURO", hex_code: "#008B8B")
Color.create(name: "GRIS DIFUSO", hex_code: "#696969")
Color.create(name: "GRIS ACEITUNA", hex_code: "#6B8E23")
Color.create(name: "VERDE MAR", hex_code: "#2E8B57")
Color.create(name: "VERDE CERCETA", hex_code: "#008080")
Color.create(name: "VIOLETA OSCURO", hex_code: "#9400D3")
Color.create(name: "VIOLETA ROJO MEDIO", hex_code: "#C71585")
Color.create(name: "NARANJA ROJO", hex_code: "#FF4500")
Color.create(name: "ACEITUNA", hex_code: "#808000")
Color.create(name: "SIENA", hex_code: "#A0522D")
Color.create(name: "AZUL PIZARRA OSCURO", hex_code: "#483D8B")
Color.create(name: "VERDE ACEITUNA OSCURO", hex_code: "#556B2F")
Color.create(name: "VERDE BOSQUE", hex_code: "#228B22")
Color.create(name: "CARMESÍ", hex_code: "#DC143C")
Color.create(name: "AZUL", hex_code: "#0000FF")
Color.create(name: "MAGENTA OSCURO", hex_code: "#8B008B")
Color.create(name: "GRIS PIZARRA OSCURO", hex_code: "#2F4F4F")
Color.create(name: "MARRÓN MONTURA", hex_code: "#8B4513")
Color.create(name: "MARRÓN", hex_code: "#A52A2A")
Color.create(name: "LADRILLO REFRACTARIO", hex_code: "#B22222")
Color.create(name: "PÚRPURA", hex_code: "#800080")
Color.create(name: "VERDE", hex_code: "#008000")
Color.create(name: "ROJO", hex_code: "#FF0000")
Color.create(name: "AZUL MEDIO", hex_code: "#0000CD")
Color.create(name: "ÍNDIGO", hex_code: "#4B0082")
Color.create(name: "AZUL MEDIANOCHE", hex_code: "#191970")
Color.create(name: "VERDE OSCURO", hex_code: "#006400")
Color.create(name: "AZUL OSCURO", hex_code: "#00008B")
Color.create(name: "AZUL MARINO", hex_code: "#000080")
Color.create(name: "ROJO OSCURO", hex_code: "#8B0000")
Color.create(name: "GRANATE", hex_code: "#800000")
Color.create(name: "NEGRO", hex_code: "#000000")

user = CreateAdminService.new.call
puts 'CREATED ADMIN USER: ' << user.email